# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: nkearney
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: sensory-minds-backend-challenge
service: website-monitoring
plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    SENDGRID_API_KEY: ${env:SENDGRID_API_KEY}
    TWILIO_ACCOUNT_SID: ${env:TWILIO_ACCOUNT_SID}
    TWILIO_AUTH_TOKEN: ${env:TWILIO_AUTH_TOKEN}
    # TWILIO_PHONE_NUMBER: ${env:TWILIO_PHONE_NUMBER}
    # TO_PHONE_NUMBER: ${env:TO_PHONE_NUMBER}
    TO_EMAIL: ${env:TO_EMAIL}
    FROM_EMAIL: ${env:FROM_EMAIL}
    GOOGLE_SHEET_ID: ${env:GOOGLE_SHEET_ID}
    GOOGLE_CLIENT_EMAIL: ${env:GOOGLE_CLIENT_EMAIL}
    GOOGLE_PRIVATE_KEY: ${env:GOOGLE_PRIVATE_KEY}
    MONITOR_URL: ${env:MONITOR_URL}

functions:
  monitor:
    handler: dist/handler.monitor
    events:
      - schedule: rate(1 minute)
