org: nkearney
app: website-monitor
service: website-monitoring
plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    TO_EMAIL: ${env:TO_EMAIL}
    GOOGLE_SHEET_ID: ${env:GOOGLE_SHEET_ID}
    MONITOR_URL: ${env:MONITOR_URL}
    GOOGLE_SHEET_NAME: ${env:GOOGLE_SHEET_NAME}
    GOOGLE_SHEET_PUBLIC_URL: ${env:GOOGLE_SHEET_PUBLIC_URL}
    ETHEREAL_PASSWORD: ${env:ETHEREAL_PASSWORD}
    ETHEREAL_EMAIL: ${env:ETHEREAL_EMAIL}
    MONGO_CONNECTION_STRING: ${env:MONGO_CONNECTION_STRING}
    DB_NAME: ${env:DB_NAME}
    DB_COLLECTION_NAME: ${env:DB_COLLECTION_NAME}

functions:
  monitor:
    handler: dist/handler.monitor
    events:
      - schedule: rate(1 minute)
